/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent.of.code.java.user;

import net.fornwall.aoc.Solver;
import net.fornwall.aoc.SolverException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void works() {
        Assertions.assertEquals("2", Solver.solve(2019, 1, 1, "14"));
    }

    @Test void throwsCorrectly() {
        Assertions.assertThrows(SolverException.class, () -> Solver.solve(2019, 1, 1, "hi"));
    }
}
