/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent.of.code.java.user;

import net.fornwall.aoc.Solver;

import java.io.IOException;
import java.nio.charset.StandardCharsets;


public class Main {

    public static void main(String[] args) throws IOException {
        var year = Integer.parseInt(args[0]);
        var day = Integer.parseInt(args[1]);
        var part = Integer.parseInt(args[2]);
        var input = new String(System.in.readAllBytes(), StandardCharsets.UTF_8);

        var answer = Solver.solve(year, day, part, input);
        System.out.println(answer);
    }
}
