name: CI

on:
  push:
  schedule:
  - cron: '0 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '19']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: ./gradlew test --info
      env:
        GRADLE_OPTS: -Xmx1024m


