name: CI

on:
  push:
  schedule:
  - cron: '0 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '21']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: ./gradlew --no-daemon test --info

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./run-docker-test.sh
